#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL with Livox MID360
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#
# Same as the stock iris airframe; the filename suffix (iris_livox) selects the
# Gazebo model (model://iris_livox = iris + livox_mid360), found via
# GAZEBO_MODEL_PATH -> simulation_assets/models. ID is in PX4's reserved custom
# range [22000, 22999].
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
